import './styles.css';
import { renderFindings, gradeBadgeHtml, summaryChipsHtml, executiveSummaryHtml, type FindingRow, type SeveritySummary } from './findings-view.js';
import { escapeHtml } from './escape-html.js';

interface ReportResponse {
    scan: {
        kind: string; status: string; score: number; grade: string; summary: SeveritySummary;
        started_at: string; completed_at: string | null; target_url: string; target_label: string | null;
    };
    findings: FindingRow[];
}

const root = document.getElementById('report-root')!;
const token = new URLSearchParams(window.location.search).get('token');

async function load(): Promise<void> {
    if (!token) {
        root.innerHTML = '<div class="card"><p class="status error">No report token provided.</p></div>';
        return;
    }
    try {
        const res = await fetch(`/api/report?token=${encodeURIComponent(token)}`);
        const data: ReportResponse = await res.json();
        if (!res.ok) throw new Error((data as unknown as { error?: string }).error || 'Report not found.');

        const { scan, findings } = data;
        root.innerHTML = `
            <div class="card">
                <h1 style="font-size:22px">${escapeHtml(scan.target_label || scan.target_url)}</h1>
                <p class="muted" style="font-size:13px">${escapeHtml(scan.target_url)} · scanned ${new Date(scan.started_at).toLocaleString()}</p>
                <div class="summary-row">${gradeBadgeHtml(scan.grade, scan.score)}</div>
                ${summaryChipsHtml(scan.summary)}
                ${executiveSummaryHtml(scan.grade, scan.score, findings)}
                <div id="report-findings" style="margin-top:16px"></div>
                <p class="muted" style="font-size:12px;margin-top:20px">This report was generated by AuditPulse using non-destructive, passive security checks. <a href="/" style="color:var(--accent)">Run your own audit →</a></p>
            </div>`;
        renderFindings(document.getElementById('report-findings')!, findings);
    } catch (err) {
        root.innerHTML = `<div class="card"><p class="status error">${escapeHtml(err instanceof Error ? err.message : 'Could not load report.')}</p></div>`;
    }
}

load();
