import type { Product } from './launches';

type Latest={name:string;tagline:string;category:string;source:string;sourceUrl:string;website?:string;launched:string;audience:string;description:string};
const accents=['#c9ff57','#7ac7ff','#ff7d66','#ffd36a','#90e0c1','#c9b7ff','#ffb7a7','#bde58d'];
const slug=(value:string)=>value.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,72);
const initials=(value:string)=>value.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join('').toUpperCase();
const latest:Latest[]=[
{name:'Fluree',tagline:'Data and context for AI and apps.',category:'Developer Tools',source:'Product Hunt',sourceUrl:'https://www.producthunt.com/products/fluree',launched:'July 24, 2026',audience:'AI developers, data teams, and application builders',description:'A data platform focused on trusted context, governed information, and application-ready data for AI systems.'},
{name:'Pushary',tagline:'Control panel for AI agents on your lock screen.',category:'AI Agents',source:'Product Hunt',sourceUrl:'https://www.producthunt.com/products/pushary',launched:'July 2026',audience:'Mobile users and teams operating AI agents',description:'Brings agent controls and status information to a mobile lock-screen experience for faster supervision.'},
{name:'Freesolo Flash',tagline:'Full-stack platform for training small language models.',category:'AI Infrastructure',source:'Product Hunt',sourceUrl:'https://www.producthunt.com/products/freesolo-flash',launched:'July 2026',audience:'ML engineers, researchers, and AI startups',description:'A training environment designed to help teams build and iterate on smaller specialized language models.'},
{name:'RunEvr',tagline:'Agentic project management environment for creatives.',category:'Project Management',source:'Product Hunt',sourceUrl:'https://www.producthunt.com/products/runevr',launched:'July 2026',audience:'Creative teams, studios, and project leads',description:'Combines project planning, collaboration, and agent-assisted execution for creative production workflows.'},
{name:'SwiftScale Software',tagline:'QA agent that tests apps the way you explain them.',category:'Testing',source:'Product Hunt',sourceUrl:'https://www.producthunt.com/products/swiftscale-software',launched:'July 2026',audience:'Software teams, QA engineers, and product managers',description:'Turns plain-language testing instructions into automated application checks and quality-assurance workflows.'},
{name:'Pulse',tagline:'A permission-aware, proactive and agentic company brain.',category:'Knowledge',source:'Product Hunt',sourceUrl:'https://www.producthunt.com/products/pulse',launched:'July 2026',audience:'Companies managing internal knowledge and permissions',description:'Connects organizational knowledge while respecting access controls and proactively surfacing useful context.'},
{name:'valv',tagline:'Your database, safe for agents to query.',category:'AI Infrastructure',source:'Product Hunt',sourceUrl:'https://www.producthunt.com/products/valv',launched:'July 2026',audience:'Developers connecting AI agents to company databases',description:'Adds a safer access layer for agent-driven database queries, analytics, and controlled information retrieval.'},
{name:'Redential',tagline:'A developer credential that proves what you built, NDA safe.',category:'Hiring',source:'Product Hunt',sourceUrl:'https://www.producthunt.com/products/redential',launched:'July 2026',audience:'Developers, recruiters, and technical hiring teams',description:'Helps developers demonstrate verified work history and project contributions without exposing confidential details.'},
{name:'MonoCloud for Startups',tagline:'One identity layer for customers, APIs, and agents.',category:'Security',source:'Product Hunt',sourceUrl:'https://www.producthunt.com/products/monocloud-for-startups',launched:'July 2026',audience:'Startups building authentication and identity systems',description:'Provides a unified identity layer for customer accounts, API access, and emerging AI-agent workflows.'},
{name:'CartAI',tagline:'The AI agent that handles checkout.',category:'E-commerce',source:'Product Hunt',sourceUrl:'https://www.producthunt.com/products/cartai',launched:'July 21, 2026',audience:'Online stores, commerce platforms, and conversion teams',description:'An agent-centered checkout product intended to reduce friction and complete purchasing tasks for shoppers.'},
{name:'ProtoFlow',tagline:'AI-powered schematic design for PCB making.',category:'Design',source:'Product Hunt',sourceUrl:'https://www.producthunt.com/products/protoflow',launched:'July 2026',audience:'Electronics engineers, hardware startups, and PCB designers',description:'Uses AI assistance to speed up electronic schematic design and early printed-circuit-board development.'},
{name:'Routebase',tagline:'Catch API drift before your customers do.',category:'Developer Tools',source:'Product Hunt',sourceUrl:'https://www.producthunt.com/products/routebase',launched:'July 2026',audience:'API teams, backend developers, and QA engineers',description:'Monitors API behavior and contract changes so teams can identify breaking drift before it reaches customers.'},
{name:'CreateOS Sandbox',tagline:'Instant hardware-isolated sandboxes for AI agents.',category:'Developer Tools',source:'Product Hunt',sourceUrl:'https://www.producthunt.com/products/createos-sandbox',launched:'July 2026',audience:'Agent developers, security teams, and infrastructure engineers',description:'Provides isolated execution environments for testing and running agent-generated code or automated tasks.'},
{name:'Nautis',tagline:'The AI-native operating system for founders.',category:'Operations',source:'Product Hunt',sourceUrl:'https://www.producthunt.com/products/nautis',launched:'July 20, 2026',audience:'Startup founders and small operating teams',description:'An all-in-one founder workspace built around AI-assisted planning, execution, and business operations.'},
{name:'Backdrop',tagline:'AI coworkers that run projects and operations.',category:'Project Management',source:'Product Hunt',sourceUrl:'https://www.producthunt.com/products/backdrop',launched:'July 2026',audience:'Operations teams, agencies, and growing startups',description:'Coordinates AI coworkers around project tasks, recurring processes, and operational execution.'},
{name:'Resume Studio',tagline:'Score and tailor your resume and practice the interview.',category:'Hiring',source:'BetaList',sourceUrl:'https://betalist.com/',launched:'July 24, 2026',audience:'Job seekers and career coaches',description:'Combines resume scoring, job-specific tailoring, and interview preparation in one career workflow.'},
{name:'StreamingBeam',tagline:'Find where any title is streaming with AI picks and expiring alerts.',category:'Entertainment',source:'BetaList',sourceUrl:'https://betalist.com/',launched:'July 24, 2026',audience:'Streaming viewers and entertainment discovery users',description:'Searches streaming availability while adding personalized recommendations and alerts for titles leaving services.'},
{name:'PutFinder',tagline:'Screen cash-secured puts with transparent rules-based ranks.',category:'Finance',source:'BetaList',sourceUrl:'https://betalist.com/',launched:'July 24, 2026',audience:'Options traders and self-directed investors',description:'Ranks cash-secured put opportunities using visible screening criteria and repeatable daily analysis.'},
{name:'TeaChecker',tagline:'Discreet profile lookup with verified results in 24 hours.',category:'Research',source:'BetaList',sourceUrl:'https://betalist.com/',launched:'July 24, 2026',audience:'Consumers seeking identity and profile verification',description:'Offers a private lookup workflow designed to return manually verified profile findings within a day.'},
{name:'BookTranslator',tagline:'Translate books, PDFs, and EPUBs with quality AI.',category:'Productivity',source:'BetaList',sourceUrl:'https://betalist.com/',launched:'July 24, 2026',audience:'Readers, publishers, researchers, and translators',description:'Translates long-form documents and books while aiming to preserve structure, tone, and reading quality.'},
{name:'PAPI',tagline:'Keep AI builds on vision with decision memory and drift checks.',category:'Developer Tools',source:'BetaList',sourceUrl:'https://betalist.com/',launched:'July 24, 2026',audience:'Product teams and developers building with AI',description:'Records product decisions and checks implementation drift so AI-assisted builds remain aligned with the original vision.'},
{name:'Monroya',tagline:'See whether AI recommends you or your competitor.',category:'Marketing',source:'BetaList',sourceUrl:'https://betalist.com/',launched:'July 22, 2026',audience:'Founders, brand teams, and AI-search marketers',description:'Runs an AI-readiness and visibility check to compare how brands appear in model-generated recommendations.'},
{name:'Insightdive',tagline:'Collect anonymous in-app feedback and auto-cluster themes.',category:'Analytics',source:'BetaList',sourceUrl:'https://betalist.com/',launched:'July 22, 2026',audience:'Product managers, researchers, and SaaS teams',description:'Captures anonymous feedback inside applications and groups recurring themes to simplify product research.'},
{name:'Heartsome',tagline:'Run hiring and HR in one place without hidden fees.',category:'Hiring',source:'BetaList',sourceUrl:'https://betalist.com/',launched:'July 22, 2026',audience:'Small businesses and people-operations teams',description:'A combined hiring and HR workspace focused on straightforward operations and transparent pricing.'},
{name:'Kane CLI by TestMu AI',tagline:'Terminal-native browser testing for developers and agents.',category:'Testing',source:'Launching Next',sourceUrl:'https://www.launchingnext.com/',website:'https://www.testmuai.com/kane-cli/',launched:'July 24, 2026',audience:'Developers, QA engineers, and coding agents',description:'Runs browser-testing workflows from the terminal for human developers and automated software agents.'},
{name:'Nuvoha',tagline:'Discover complete trips personalized around you.',category:'Travel',source:'Launching Next',sourceUrl:'https://www.launchingnext.com/',website:'https://nuvoha.app',launched:'July 24, 2026',audience:'Travelers planning personalized itineraries',description:'Builds trip recommendations around user preferences rather than requiring travelers to assemble every detail manually.'},
{name:'Tradoshi',tagline:'Smart trading journal with an AI discipline coach.',category:'Finance',source:'Launching Next',sourceUrl:'https://www.launchingnext.com/',website:'https://tradoshi.com/en/',launched:'July 24, 2026',audience:'Active traders and investing coaches',description:'Combines trade journaling with AI-driven reflection intended to improve consistency and trading discipline.'},
{name:'BigIdeasDB',tagline:'Find proven problems and build your next product.',category:'Research',source:'Launching Next',sourceUrl:'https://www.launchingnext.com/',website:'https://bigideasdb.com',launched:'July 24, 2026',audience:'Founders, product researchers, and indie makers',description:'A searchable idea and problem database for finding validated pain points before choosing what to build.'},
{name:'Store & Forget',tagline:'Snap an item, auto-fill its details, and find it later.',category:'Productivity',source:'Launching Next',sourceUrl:'https://www.launchingnext.com/',website:'https://affiliate-marketing-jorc.bolt.host/',launched:'July 24, 2026',audience:'Households and people organizing stored belongings',description:'Uses photos and automatic descriptions to create a searchable record of items placed in storage.'},
{name:'Headshot.ltd',tagline:'Selfie in. Professional headshot out.',category:'Creative AI',source:'Launching Next',sourceUrl:'https://www.launchingnext.com/',website:'https://headshot.ltd/',launched:'July 24, 2026',audience:'Professionals, job seekers, and remote teams',description:'Transforms uploaded selfies into polished professional headshots for profiles, resumes, and company pages.'},
{name:'ARK',tagline:'All customer conversations in one AI-powered inbox.',category:'Customer Support',source:'Launching Next',sourceUrl:'https://www.launchingnext.com/',website:'https://byark.ai/en',launched:'July 24, 2026',audience:'Support, sales, and customer-success teams',description:'Centralizes customer conversations and applies AI assistance to triage, understand, and respond from one inbox.'},
{name:'Keepvio',tagline:'Organize tasks, notes, and projects in one workspace.',category:'Productivity',source:'Launching Next',sourceUrl:'https://www.launchingnext.com/',website:'https://www.keepvio.com/',launched:'July 24, 2026',audience:'Individuals and small teams managing daily work',description:'A unified productivity workspace for combining notes, tasks, and lightweight project organization.'},
{name:'tiun',tagline:'Payments backend for indie hackers.',category:'Finance',source:'Microlaunch',sourceUrl:'https://microlaunch.net/',launched:'July 2026',audience:'Indie developers and SaaS founders',description:'Combines authentication, payments, database services, and merchant-of-record support in a developer-focused backend.'},
{name:'VibeMyWay',tagline:'Ship a complete content package while you eat lunch.',category:'Marketing',source:'Microlaunch',sourceUrl:'https://microlaunch.net/',launched:'July 2026',audience:'Founders, creators, and small marketing teams',description:'A content-production tool positioned around quickly creating a full set of campaign-ready marketing materials.'},
{name:'InnerVeda',tagline:'AI Ayurveda that remembers you without streaks or guilt.',category:'Health',source:'Tiny Startups',sourceUrl:'https://www.tinystartups.com/launches/2026/7',launched:'July 2026',audience:'Wellness users interested in personalized Ayurveda guidance',description:'Provides memory-aware Ayurveda guidance designed around ongoing wellness support rather than habit streak pressure.'}
];
export const latestMultisource:Product[]=latest.map((item,index)=>({id:`latest-${slug(item.name)}`,name:item.name,initials:initials(item.name),category:item.category,tagline:item.tagline,description:item.description,audience:item.audience,pricing:'Visit listing for details',launched:item.launched,freshness:135-index,accent:accents[index%accents.length],tags:[item.category,item.source,'New launch'],url:item.website||item.sourceUrl,website:item.website,source:item.source,sourceUrl:item.sourceUrl}));
