export const julySeeds=[
['Acti','Agentic keyboard for mobile commands and search','Productivity','July 1'],
['Humalike','Give your AI agents the social intelligence they are missing','AI Infrastructure','July 1'],
['Tabstack Browser Automation','Automate the web in your app or agent, no browser to host','Developer Tools','July 1'],
['Claude Sonnet 5','AI that plans, acts, and gets work done','AI Agents','July 1'],
['Adam CAD Copilot','AI CAD inside Onshape and Fusion','Design','July 1'],
['MailAdept by mailwarm','AI agents and email deliverability experts on your team','Marketing','July 1'],
['Modelence Mobile Builder','Build mobile apps by chatting with AI','Developer Tools','July 1'],
['Sequence Agentic','Money movement for AI agents','Finance','July 1'],
['Fuser Apps','Vibecode apps, sites and games on a shared canvas','No-code','July 1'],
['Mark by Airtop','Vibe automation for solo marketers','Marketing','July 1'],
['Gemini Omni Flash','High-quality video generation and conversational editing','Creative AI','July 1'],
['Claude Science','Your research partner for rigorous science','Knowledge','July 1'],
['OASIS 1 Ring','Whisper to write and touch to edit','Productivity','July 1'],
['RunInfra','Describe the AI model you need and get an optimized deployment','AI Infrastructure','July 1'],
['N71','Give all your AI agents one shared context','AI Infrastructure','July 1'],
['Metal','AI-driven operating system for raising venture rounds','Finance','July 1'],
['Stigg 2.0','The usage runtime for AI products','Developer Tools','July 1'],
['Fypro','Convert your TikTok followers into paying customers','E-commerce','July 2'],
['Needle','The proactive GTM agent in Slack and Teams','Sales','July 2'],
['PixFit','Turn one creative into every ad format instantly','Marketing','July 2'],
['Macro','Unify your work into one app with shared memory','Productivity','July 2'],
['Solaris','Your company AI adoption and upskilling platform','Education','July 2'],
['Banger Mail','Shared mailboxes for teams and AI agents','Productivity','July 2'],
['PieterPost MCP','Connect your AI agent to postal mail','Developer Tools','July 2'],
['scritty','Shared searchable memory for every AI coding agent','Developer Tools','July 2'],
['Sidedoor','Paste any job and find who in your network can refer you','Hiring','July 2'],
['Macuse','Give your AI superpowers on macOS','Productivity','July 2'],
['html.contact','A full form backend you can test before paying','Developer Tools','July 2'],
['Basedash Actions','A BI tool that can take action for you','Analytics','July 2'],
['Flowly','A personal AI agent that runs on desktop and iPhone','AI Agents','July 2'],
['Gaming Chat SDK by CometChat','Chat that drops into Unreal like it was always there','Developer Tools','July 2'],
['Retrace','Debug AI agents by replaying and forking runs','Developer Tools','July 2'],
['Quick Sub 2','Creative video subtitling with direct canvas control','Video','July 2'],
['Glaze by Raycast','Create your own Mac apps by chatting with AI','No-code','July 3'],
['Goals from Loops','Measure whether a campaign drove the desired outcome','Marketing','July 3'],
['Tamamon','A desktop pet that grows as you code with Claude Code','Developer Tools','July 3'],
['Archify','Understand software architecture faster','Developer Tools','July 3'],
['nxt','Talk to your to-do list and get what is next','Productivity','July 3'],
['Vox','Voice in and voice out with GitHub Copilot','Developer Tools','July 3'],
['Vida','Clone yourself and let AI do the work before you ask','AI Agents','July 4'],
['ChecklistFox','AI checklist maker for polished PDFs','Productivity','July 4'],
['PhoneDeck','Turn your iPhone into a free Mac controller','Productivity','July 4'],
['CentryAI','A subscription tracker built for forgotten renewals','Finance','July 4'],
['Termi Protocol','Watch AI coding agents build live in 3D','Developer Tools','July 4'],
['WorkBuddy','Produce stronger results with a team of AI experts','Productivity','July 5'],
['DocsAlot','Documentation that works for humans and AI systems','Knowledge','July 5'],
['Endl','A global operating account for fiat, stablecoins and cards','Finance','July 5'],
['TryCase','Disposable test environments for AI coding agents','Developer Tools','July 5'],
['MentionDrop MCP','Give your AI agent live market signals','Marketing','July 5'],
['CircleChat','Give AI agents a Slack, task board and manager','AI Agents','July 5'],
['Pennen','One quiet handwritten page a day with no feed','Productivity','July 5'],
['Toku Reader','Read and listen to native Japanese and Chinese','Education','July 5'],
['Typeahead 2.0','Private AI autocomplete for every app on your Mac','Productivity','July 6'],
['Octolens','Social listening for the agent era','Marketing','July 6'],
['Sunrise','A real planner for Google Tasks','Productivity','July 6'],
['AirKaren','AI that fights customer service for you','Customer Success','July 6'],
['Stanley Studio','An AI video editor that edits like a human','Video','July 6'],
['Edgee Claude Code Compressor V2','Use fewer tokens with the same coding context','Developer Tools','July 6'],
['Astryx','A customizable agent-ready open-source design system','Design','July 6'],
['CodeMote','Drive Claude Code, Codex and CLI agents from iPhone','Developer Tools','July 6'],
['Nixmac','Nix-darwin that speaks plain English','Developer Tools','July 6'],
['Mozaik','TypeScript runtime for self-organizing AI agents','Developer Tools','July 6'],
['Cadence','Record once and send confidently','Productivity','July 6'],
['Badge','AI agents collect peer reviews to generate proof of work','Hiring','July 7'],
['Katalyst','The AI agent that works your Salesforce pipeline','Sales','July 7'],
['Scribble Network','Make AI recommend your brand','Marketing','July 7'],
['Dupely','The trust layer for online shopping','E-commerce','July 7'],
['Mira','AI-moderated interviews that read how people feel','Analytics','July 7'],
['AI Emaily','An AI inbox that writes like you and replies automatically','Productivity','July 7'],
['Ellis','AI notes for in-person meetings','Productivity','July 7'],
['Social Fetch','Social media scraper API for major platforms','Developer Tools','July 7'],
['Ogment AI','An AI coworker in Slack','AI Agents','July 7'],
['LongCat-2.0','A large open-source MoE model trained on AI ASICs','AI Infrastructure','July 7'],
['Glideo','Screen recordings that edit themselves','Video','July 7'],
['Zoho Tables','A smarter way to manage work and data','Productivity','July 7'],
['IvyForms','A WordPress form builder for real workflows','No-code','July 8'],
['Willow Frontier Pro','Fast and accurate dictation for professional work','Productivity','July 8'],
['Bono AI','Talk once and publish everywhere','Marketing','July 8'],
['Link Preview API','Get Open Graph data, titles and images for any URL','Developer Tools','July 8'],
['LemonLime','Automate existing workflows with a single prompt','AI Agents','July 8'],
['Orbit for Mac','Every Google account in a single window','Productivity','July 8'],
['PopTask for Apple','Turn to-dos into scheduled tasks','Productivity','July 8'],
['agents-cli','The CLI coding agents use to ship agents','Developer Tools','July 8'],
['Orus','Claude-style analysis for investing in perpetuals','Finance','July 8'],
['New small business tools by IFTTT','Run business workflows with HubSpot, Figma and more','Productivity','July 8'],
['Universal-3.5 Pro','High-accuracy speech-to-text from AssemblyAI','AI Infrastructure','July 8'],
['Notion Agents iOS app','Chat with Notion Agents anywhere','Productivity','July 8'],
['NanoKVM-Go','Give an AI agent physical control over any screen','Developer Tools','July 8'],
['Auriko','A trading desk for LLM calls','AI Infrastructure','July 9'],
['Timbal AI','Build AI agents, workflows and apps in one stack','Developer Tools','July 9'],
['Perfai Security','Find and fix live vulnerabilities in vibe apps','Security','July 9'],
['Toyo','An executive assistant that lives in iMessage and calls you','AI Agents','July 9'],
['Lispr','Hold a key, speak and write anywhere','Productivity','July 9'],
['Opper AI','A European AI gateway for agents','AI Infrastructure','July 9'],
['GPT-Live','Full-duplex voice for ChatGPT','Voice AI','July 9'],
['Aura Agents Git Intent','Open-source IDE for controlling AI coding agents','Developer Tools','July 9'],
['Monogram AI','AI with a visual and interactive interface','Productivity','July 9'],
['Tasks.txt','Plain-text task manager for macOS','Productivity','July 9'],
['Coasty','A computer-use agent that runs legacy software','AI Agents','July 9'],
['Just Ask by SEORCE','Talk to SEO and AI visibility data on WhatsApp','Marketing','July 9'],
] as const;
