export const juneSeeds=[
['Cursor for iOS','Build with coding agents from anywhere','Developer Tools','June 30'],
['Skills Marketplace by Databox','Ready-made AI analytics skills for your business data','Analytics','June 30'],
['Foresight by Lightning Rod','Predict anything with AI','Developer Tools','June 30'],
['Akiflow','Manage tasks and calendars from Claude, ChatGPT or Cursor','Productivity','June 30'],
['Supafax','Email-native assistant that learns how you work','Productivity','June 30'],
['v0 Design Systems 2.0','Build with your components, colors, fonts, and patterns','Developer Tools','June 30'],
['Dayflow','Open source tools that help you get promoted','Productivity','June 30'],
['Pluno','Browser agent that is faster than traditional browser automation','AI Agents','June 30'],
['AgentPeek','Your coding agents in the Mac notch','Developer Tools','June 30'],
['Tinkerfont','Free font playground for live websites','Design','June 30'],
['Brain2Qwerty v2','Decode sentences directly from non-invasive brain signals','AI Infrastructure','June 30'],
['Load Nova','AI copilot and dashboard built for dispatcher speed','Operations','June 30'],
['Justwrite','A private local-first writing space that works offline','Productivity','June 30'],
['Oakamo','Your quiet space for reading articles later','Productivity','June 30'],
['Clade','AI COO that runs your team in tools you already use','AI Agents','June 30'],
['Spira for Product Hunt Makers','Social media growth agents that build your momentum','Marketing','June 29'],
['Agent Mode by Receiptor AI','Bookkeeping assistant that runs receipt workflows end-to-end','Finance','June 29'],
['ClinePass','Run the best open-weights models in Cline','Developer Tools','June 29'],
['VisibAI','Find and improve your visibility in AI answers','Marketing','June 29'],
['PMB','Stop re-explaining your project to AI coding agents','Developer Tools','June 29'],
['Sami','Automate ad budgets across Google, LinkedIn and Meta','Marketing','June 29'],
['Crest','System stats and translation on your Mac notch','Productivity','June 29'],
['ReadHere','Lightweight PDF and EPUB reader in your browser','Productivity','June 29'],
['Outpaint - Ad Reframe','Turn vertical UGC into widescreen ads for YouTube and TV','Video','June 29'],
['Intelli','Convert leads into customers with AI conversations','Sales','June 29'],
['Upstream FTP','A fast native FTP and SFTP client for macOS','Developer Tools','June 29'],
['Mailgent','AI agents that can email, pay APIs, sign and store secrets','AI Agents','June 29'],
['TanStarter','Ship faster with TanStack and Cloudflare','Developer Tools','June 29'],
['Loop by ads.expert','Flight simulator for paid media with an AI coach','Marketing','June 29'],
['Blinked','LinkedIn outreach built for compliant prospecting','Sales','June 29'],
['discode.ai','100+ AI models in one interface','AI Infrastructure','June 28'],
['Persona.js','Add WebMCP-native AI chat to any frontend','Developer Tools','June 28'],
['GetCompress','Lossless media compression without context switching','Productivity','June 28'],
['Dotient','Your local semantic search app','Productivity','June 28'],
['Lyto','One AI agent across your browser, tools and messages','AI Agents','June 28'],
['Wirable','Test whether AI agents can use your product','Developer Tools','June 28'],
['kodwai','Score how well your vibe-coded product is built','Developer Tools','June 28'],
['Weavz.io','Let AI agents safely act in customer apps','AI Infrastructure','June 28'],
['DevGlobe','Where developers build in public on a live globe','Community','June 28'],
['Salestrics Resolve Beta','AI-native service desk for startups','Customer Success','June 28'],
['Schema Source by Tabstack','Turn any URL into JSON Schema, Zod or Pydantic','Developer Tools','June 28'],
['AI-native Continuous Planning Platform','Turn product fit into PRDs and assigned work','Operations','June 28'],
['FocusStack','Understand, improve and protect your focus','Productivity','June 28'],
['VersaVoice AI','Natural voice translation without robotic output','Voice AI','June 28'],
['Auto-Immo PRO 2.0','Turn property scans into plans, 3D reports and estimates','Operations','June 28'],
['QApilot CoWork','Scale mobile automation without scaling the QE team','Developer Tools','June 27'],
['Folio AI','Claude for PowerPoint on steroids','Productivity','June 27'],
['Nada','Compose music with just your voice','Creative AI','June 27'],
['RetroMac','Turn your Mac into a time machine','Productivity','June 27'],
['Cloud World Model','Simulate AWS, GCP and DigitalOcean without the bill','Developer Tools','June 27'],
['Epilogue','Professional book-writing app for serious authors','Productivity','June 27'],
['Supra Player','Compare and sync videos fast','Video','June 27'],
['Wysera','One AI agent for content, CRM and operations','AI Agents','June 27'],
['OpenBot','Tag specialized agents like friends or employees','AI Agents','June 27'],
['Velocity 2.0 Prompt Co-Pilot','One-click prompt enhancement for any AI tool','Productivity','June 27'],
['FeedVector','Turn LinkedIn posts and comments into clients','Marketing','June 27'],
['VibeRaven','Production protocol for AI-built apps','Developer Tools','June 27'],
['Letter Maps','Free teleprompter that follows your voice','Video','June 27'],
['ButDoc','Free PDF editor and signing tool online','Productivity','June 27'],
['Futbol.so','Modern software for football communities','Community','June 27'],
['Agent Arena','A public arena where AI agents compete','Community','June 26'],
['Gemini Spark','A 24/7 personal AI agent','AI Agents','June 26'],
['Atlas Company Context','Give every AI tool knowledge of your company','AI Infrastructure','June 26'],
['note.md','Notes and research documents as local LLM memory','Knowledge','June 26'],
['SquidHub','Multiplayer mode for humans and AI','Productivity','June 26'],
['ModuleX','AI workspace connected to everything','No-code','June 26'],
['Sleek Analytics','See who is on your site right now','Analytics','June 26'],
['LockIn MCP','Let AI block distractions for you','Productivity','June 26'],
['Crodox','Slice tasks out of a codebase and merge them back cleanly','Developer Tools','June 26'],
['AI Slide Editor by CubeOne','The slide editor PowerPoint should have shipped','Productivity','June 26'],
['Basedash for Excel','Turn an Excel file into a live dashboard','Analytics','June 26'],
['PixelDrivePro','API and MCP-first bulk image generation','Creative AI','June 26'],
['DMV by Agent Community','Community-governed namespace for AI agents','Developer Tools','June 26'],
['Animdock Motion Templates','Create trend-ready motion graphics in the browser','Design','June 26'],
['Group Subscriptions by beehiiv','Sell newsletter subscriptions to teams','Marketing','June 26'],
['BrowserAct','Browser automation for agents and teams','AI Agents','June 25'],
['Zaro','AI workspace for faster business execution','Productivity','June 25'],
['Oxlo.ai','Automate operational work with AI','Operations','June 25'],
['Brain2 by ClickUp','An AI work brain connected to your projects','Productivity','June 25'],
['Figma Motion','Create motion directly inside Figma workflows','Design','June 25'],
['Polygraph','Understand and improve AI-generated work','Analytics','June 25'],
['Tough Tongue AI for Sales','Practice difficult sales conversations with AI','Sales','June 25'],
['Samepage Signals','Turn team activity into useful operating signals','Analytics','June 25'],
['Nixmac','Clean and manage your Mac with confidence','Productivity','June 25'],
['Genspark Design','Create polished design assets with AI','Creative AI','June 25'],
['MeetPoint','Coordinate meetings and shared availability','Productivity','June 25'],
['Postproxy Engagement API','API for social engagement workflows','Developer Tools','June 25'],
['Sidegent','AI sidekick for everyday browser tasks','AI Agents','June 25'],
['SendTidings','Send thoughtful updates and newsletters','Marketing','June 25'],
['BrowserBash','Automate repeatable browser work','Developer Tools','June 25'],
['Tencent EdgeOne Makers','Build and deploy web experiences at the edge','Developer Tools','June 24'],
['Propane','AI workspace for product and operations teams','Operations','June 24'],
['Crewdle AI','Private AI collaboration for distributed teams','Productivity','June 24'],
['Stripe.Directory','Discover software and businesses built with Stripe','Finance','June 24'],
['Mindstone Rebel','AI learning workspace for modern professionals','Education','June 24'],
['Customer Relationship Agents by Clarify','AI agents that maintain customer relationships','Customer Success','June 24'],
['Buy by Agentcard','Enable AI agents to make controlled purchases','Finance','June 24'],
['React UI Kit V7','Production-ready React components for modern apps','Developer Tools','June 24'],
['Ruby','AI teammate for business workflows','AI Agents','June 24'],
['StaleMate PR','Detect and revive stale pull requests','Developer Tools','June 24'],
['Swimio','Manage swim teams and performance data','Operations','June 24'],
['TaskFord','Structured task management for focused teams','Productivity','June 24'],
['FUTO Swipe','Private keyboard and swipe typing software','Productivity','June 24'],
['Nimt','Simple team knowledge and collaboration','Knowledge','June 24'],
['Liner Developer Platform','Build with Liner search and AI capabilities','Developer Tools','June 24'],
['OpenArt Director','Direct creative AI generation with more control','Creative AI','June 23'],
['Bluerails Discovery','Discover and qualify opportunities with AI','Sales','June 23'],
['Cotypist','AI copilot for focused writing','Productivity','June 23'],
['Latitude','Build and evaluate prompts and AI workflows','Developer Tools','June 23'],
['Thumbmagic','Create higher-converting thumbnails with AI','Marketing','June 23'],
['Hush','Private AI workspace for sensitive work','AI Infrastructure','June 23'],
['Swytchcode CLI','Switch and manage coding environments from the terminal','Developer Tools','June 17'],
['Daemons by Charlie Labs','Persistent AI workers for recurring tasks','AI Agents','June 17'],
['Quartz','Modern workspace for structured knowledge','Knowledge','June 17'],
['Dopami','AI productivity for daily work','Productivity','June 17'],
['Tapfree for Chrome','Navigate and act in the browser without repetitive clicks','Productivity','June 17'],
['Deep Work Plan','Plan focused sessions and protect deep work','Productivity','June 17'],
['Locus Founder','Operating workspace for startup founders','Operations','June 17'],
['Tyto by ai-coustics','Improve spoken audio quality with AI','Voice AI','June 17'],
['memi','Personal memory layer for AI assistants','AI Infrastructure','June 17'],
['Dualora','Collaborative AI workspace for teams','AI Agents','June 17'],
['ClawEase','Simplify agent setup and automation','AI Agents','June 17'],
['Kepler','Explore and analyze data with AI','Analytics','June 17'],
['Typerino','Fast text expansion and writing automation','Productivity','June 17'],
['ClipDone','Turn long video into finished clips','Video','June 17'],
['Mirlo','Independent music publishing and community tools','Community','June 17'],
['Goldfish','AI memory for teams and customer conversations','Knowledge','June 16'],
['Invoko','Automate outreach and follow-up workflows','Sales','June 16'],
['Zoona AI','AI teammate for business operations','AI Agents','June 16'],
['MakersClaw','Agent-powered workspace for makers','AI Agents','June 16'],
['PeakRoutine','Plan and track high-performance routines','Productivity','June 16'],
['Edgee Turbo Models','Fast edge-hosted AI models','AI Infrastructure','June 16'],
['GitHits beta 0.9','Analytics and discovery for GitHub projects','Analytics','June 16'],
['Stride','Coordinate projects with a lighter workflow','Productivity','June 16'],
['MindReader v1','Understand customer intent with AI','Analytics','June 16'],
['Dirac','AI tools for scientific and technical teams','Developer Tools','June 16'],
['Subotiz','Automate subtitles and video localization','Video','June 16'],
['DevCleaner','Clean development files and reclaim disk space','Developer Tools','June 16'],
['Voiden','API development workspace for modern teams','Developer Tools','June 16'],
['Revyl','Test mobile apps with AI-assisted automation','Developer Tools','June 16'],
['Voice Calls in Chatwoot','Handle customer voice calls inside Chatwoot','Customer Success','June 16'],
['Wobo','AI workspace for job search and career workflows','Productivity','June 15'],
['Novu Connect','Connect notification infrastructure to your app','Developer Tools','June 15'],
['PandaProbe Cloud','Monitor websites and APIs from the cloud','Developer Tools','June 15'],
['AutoEdit','Edit content automatically with AI','Creative AI','June 15'],
['Kickbacks.ai','Automate partner and referral rewards','Marketing','June 15'],
['AEVS','AI-assisted video production system','Video','June 15'],
['Fonda','Modern finance operations for startups','Finance','June 15'],
['Notra Image Generation','Generate brand-ready images with AI','Creative AI','June 15'],
['Sulsaly','AI assistant for sales operations','Sales','June 15'],
['MockPilot','Create and test product mockups quickly','Design','June 15'],
['Reignat','AI workspace for research and decisions','Knowledge','June 15'],
['Synopsule','Turn complex information into concise briefs','Productivity','June 15'],
['Relay','Automate cross-tool workflows with humans in the loop','Operations','June 15'],
['Dropmatico','Automate file delivery and digital product workflows','E-commerce','June 15'],
['MiMo Code','AI coding assistant for developers','Developer Tools','June 15'],
['Slashy','Fast command palette for your workflows','Productivity','June 14'],
['Taste Lab','Research and organize food preferences with AI','Consumer','June 14'],
['Permute 4.0','Transform files and media on Mac','Productivity','June 14'],
['Athenic 2.0','Ask business data questions in natural language','Analytics','June 14'],
['Cloudback for Linear','Back up Linear issues and project data','Developer Tools','June 14'],
['Conan','AI assistant for product and engineering teams','AI Agents','June 14'],
['Memoriq','Persistent memory for AI applications','AI Infrastructure','June 14'],
['Allergo','Track allergies and health information privately','Health','June 14'],
['Reverie.fm','Personalized ambient audio for focus and sleep','Voice AI','June 14'],
['LabelLens','Understand product labels with computer vision','Consumer','June 14'],
['Baroque','Create refined visual assets with AI','Creative AI','June 14'],
['1ClickReport','Generate client-ready reports in one click','Analytics','June 14'],
['Hive','Collaborative workspace for distributed teams','Productivity','June 14'],
['Web Researcher MCP','Research the web through an MCP server','Developer Tools','June 14'],
['Roast My Resume','Get direct AI feedback on your resume','Hiring','June 14'],
['Vercel Drop','Drop a project and make it live','Developer Tools','June 13'],
['Kimi K2.7 Code','Kimi coding model for software development','Developer Tools','June 13'],
['Prometheus by Firecrawl','Forward-deployed agent for web data','AI Infrastructure','June 13'],
['CakewordAI','Point at anything to learn its name in any language','Education','June 13'],
['NomNak','Find restaurants through people you trust','Community','June 13'],
['Avatars in ElevenCreative','Create talking-head video avatars','Video','June 13'],
['Carve','Create client-ready architectural renders quickly','Design','June 13'],
['Feezza','AI health companion connecting food to how you feel','Health','June 13'],
['ScrollJail','Ask why before opening distracting social apps','Productivity','June 13'],
['TiniAid','Soundscapes for ADHD focus and calm','Health','June 13'],
['GameBrain API','Video game database API with extensive coverage','Developer Tools','June 13'],
['Praise.page','Collect product testimonials quickly','Marketing','June 13'],
['PayRam Payment Gateway for AI Agents','Payment gateway designed for autonomous agents','Finance','June 13'],
['APIddress Email Validation API','Email validation API that explains results','Developer Tools','June 13'],
['CawCut','AI-powered workflow for creators','Video','June 13'],
['Firma.dev','Low-cost e-signature API for apps','Developer Tools','June 12'],
['Qursor','Point at any UI and send exact context to AI','Developer Tools','June 12'],
['Pond','Fundraising, go-to-market and bounties for startups','Operations','June 12'],
['HyperSleep','Block social media until you have slept','Health','June 12'],
['KOSH Money','USD accounts and credit cards for freelancers','Finance','June 12'],
['Bob\'s CLI','Local-first AI coding CLI that adapts to you','Developer Tools','June 12'],
['ShellMate','Manage SSH servers, credentials and teams','Developer Tools','June 12'],
['Meet Warren 3.0','Voice-supported AI financial planning partner','Finance','June 12'],
['CueBuddy','Record talking videos without manual scrolling','Video','June 12'],
['Medicyn','Keep your medical history privately on-device','Health','June 12'],
['Tide Voice Notes','Layered voice notes that paint themselves','Productivity','June 12'],
['LocIn AI','Localize apps with tone-aware AI workflows','Developer Tools','June 12'],
['NODUS PH Radar','Product Hunt analytics beyond the daily leaderboard','Analytics','June 12'],
['Slack Data Agent','Ask questions about your data from Slack','Analytics','June 12'],
['Keep 3D Clock','Full-screen 3D clock scenes for iPhone and Mac','Productivity','June 12'],
] as const;
