import PDFDocument from 'pdfkit';
import { severityColor } from '../../api/_lib/email.js';

export type PdfSeveritySummary = { critical: number; high: number; medium: number; low: number; info: number };

export interface PdfFinding {
    title: string;
    severity: keyof PdfSeveritySummary;
    impact: string;
    description: string;
    evidence?: string | null;
    remediation: string;
    reference_links?: string[] | null;
    affected_url?: string | null;
}

export interface AuditPdfParams {
    targetLabel: string;
    targetUrl: string;
    hostname: string;
    scanDate: Date;
    kind: 'quick' | 'full';
    grade: string;
    score: number;
    summary: PdfSeveritySummary;
    findings: PdfFinding[];
    reportUrl: string;
    verifiedOwnership: boolean;
    autoRescan: boolean;
}

const INK = '#141922';
const MUTED = '#6b7385';
const LINE = '#dfe3ea';
const PAGE_MARGIN = 50;

const SEVERITY_ORDER: (keyof PdfSeveritySummary)[] = ['critical', 'high', 'medium', 'low', 'info'];
const SEVERITY_LABEL: Record<keyof PdfSeveritySummary, string> = {
    critical: 'Critical', high: 'High', medium: 'Medium', low: 'Low', info: 'Info',
};

/**
 * Writing this close to the page's bottom edge falls inside pdfkit's
 * default bottom margin, which makes `.text()` think the content overflows
 * and silently appends a fresh blank page to fit it — zeroing the margin
 * for the duration of the footer write (and using `lineBreak: false`, which
 * skips the overflow check entirely) avoids that.
 */
function drawFooter(doc: PDFKit.PDFDocument): void {
    const range = doc.bufferedPageRange();
    const originalBottomMargin = doc.page.margins.bottom;
    for (let i = range.start; i < range.start + range.count; i++) {
        doc.switchToPage(i);
        doc.page.margins.bottom = 0;
        const bottom = doc.page.height - 32;
        doc.fontSize(8).fillColor(MUTED).font('Helvetica')
            .text('Generated by AuditPulse — non-destructive, passive security audit', PAGE_MARGIN, bottom, { lineBreak: false });
        doc.fontSize(8).fillColor(MUTED)
            .text(`Page ${i - range.start + 1} of ${range.count}`, doc.page.width - PAGE_MARGIN - 120, bottom, { width: 120, align: 'right', lineBreak: false });
        doc.page.margins.bottom = originalBottomMargin;
    }
}

/** Builds a two-part PDF: a certificate-style cover page (proof-of-audit for sharing/records) followed by the full findings appendix. Resolves to the complete PDF as a Buffer. */
export function generateAuditPdf(params: AuditPdfParams): Promise<Buffer> {
    const doc = new PDFDocument({ size: 'A4', margin: PAGE_MARGIN, bufferPages: true, info: { Title: `AuditPulse report — ${params.targetLabel}`, Author: 'AuditPulse' } });

    const chunks: Buffer[] = [];
    const done = new Promise<Buffer>((resolve, reject) => {
        doc.on('data', chunk => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);
    });

    renderCoverPage(doc, params);
    if (params.findings.length) {
        doc.addPage();
        renderFindingsAppendix(doc, params);
    }

    drawFooter(doc);
    doc.end();
    return done;
}

function renderCoverPage(doc: PDFKit.PDFDocument, p: AuditPdfParams): void {
    doc.rect(0, 0, doc.page.width, 130).fill('#0b0e14');
    doc.fillColor('#35e0a1').font('Helvetica-Bold').fontSize(22).text('AuditPulse', PAGE_MARGIN, 40);
    doc.fillColor('#93a0b5').font('Helvetica').fontSize(11).text('Security Audit Report', PAGE_MARGIN, 68);
    doc.fillColor('#93a0b5').fontSize(9).text(`Generated ${p.scanDate.toLocaleString('en-US', { dateStyle: 'long', timeStyle: 'short' })}`, PAGE_MARGIN, 88);

    let y = 160;
    doc.fillColor(INK).font('Helvetica-Bold').fontSize(18).text(p.targetLabel, PAGE_MARGIN, y);
    y += 24;
    doc.fillColor(MUTED).font('Helvetica').fontSize(11).text(p.targetUrl, PAGE_MARGIN, y);
    y += 30;

    // Grade block
    const bucket = p.grade.startsWith('A') ? '#0f9d6e' : p.grade.startsWith('B') ? '#5a9d0f' : p.grade.startsWith('C') ? '#b8860b' : '#c23a52';
    doc.roundedRect(PAGE_MARGIN, y, 90, 90, 12).fillAndStroke('#f4f6f9', LINE);
    doc.fillColor(bucket).font('Helvetica-Bold').fontSize(40).text(p.grade, PAGE_MARGIN, y + 20, { width: 90, align: 'center' });
    doc.fillColor(MUTED).font('Helvetica').fontSize(8).text('GRADE', PAGE_MARGIN, y + 68, { width: 90, align: 'center' });

    const infoX = PAGE_MARGIN + 110;
    doc.fillColor(INK).font('Helvetica-Bold').fontSize(13).text(`Security score: ${p.score}/100`, infoX, y + 6);
    doc.fillColor(MUTED).font('Helvetica').fontSize(10).text(
        `${SEVERITY_ORDER.map(s => `${p.summary[s]} ${SEVERITY_LABEL[s]}`).join('  ·  ')}`,
        infoX, y + 26, { width: doc.page.width - infoX - PAGE_MARGIN },
    );
    doc.fillColor(MUTED).fontSize(10).text(`Audit type: ${p.kind === 'full' ? 'Full audit (crawled, deep checks)' : 'Quick check'}`, infoX, y + 46);
    doc.fillColor(MUTED).fontSize(10).text(`Domain ownership: ${p.verifiedOwnership ? 'Verified' : 'Not verified'}`, infoX, y + 62);
    y += 110;

    doc.moveTo(PAGE_MARGIN, y).lineTo(doc.page.width - PAGE_MARGIN, y).strokeColor(LINE).stroke();
    y += 20;

    doc.fillColor(INK).font('Helvetica-Bold').fontSize(12).text('What this certifies', PAGE_MARGIN, y);
    y += 18;
    const certText = `AuditPulse ran ${p.findings.length ? p.findings.length + ' automated, non-destructive security ' + (p.findings.length === 1 ? 'check' : 'checks') + ' against' : 'an automated, non-destructive security audit against'} ${p.hostname} on ${p.scanDate.toLocaleDateString('en-US', { dateStyle: 'long' })}. The audit is entirely passive — it reads public responses (headers, TLS configuration, cookies, page content) and never attempts exploitation, brute-forcing, or any action that could disrupt the target. ` +
        (p.autoRescan ? 'This site is on automatic monthly re-audit, so this result reflects the current state of the site as of the date above.' : 'This is a point-in-time result; re-run the audit periodically to keep it current.');
    doc.fillColor(MUTED).font('Helvetica').fontSize(10).text(certText, PAGE_MARGIN, y, { width: doc.page.width - PAGE_MARGIN * 2, lineGap: 3 });
    y = doc.y + 24;

    doc.fillColor(INK).font('Helvetica-Bold').fontSize(12).text('Full interactive report', PAGE_MARGIN, y);
    y += 16;
    doc.fillColor('#0f9d6e').font('Helvetica').fontSize(10).text(p.reportUrl, PAGE_MARGIN, y, { link: p.reportUrl, underline: true });
    y = doc.y + 30;

    if (p.findings.length) {
        doc.fillColor(INK).font('Helvetica-Bold').fontSize(12).text('Findings summary', PAGE_MARGIN, y);
        y += 18;
        for (const sev of SEVERITY_ORDER) {
            if (!p.summary[sev]) continue;
            doc.circle(PAGE_MARGIN + 4, y + 5, 4).fill(severityColor(sev));
            doc.fillColor(INK).font('Helvetica').fontSize(10).text(`${SEVERITY_LABEL[sev]} — ${p.summary[sev]}`, PAGE_MARGIN + 16, y);
            y += 16;
        }
    } else {
        doc.fillColor('#0f9d6e').font('Helvetica-Bold').fontSize(11).text('No issues found by these checks.', PAGE_MARGIN, y);
    }
}

function renderFindingsAppendix(doc: PDFKit.PDFDocument, p: AuditPdfParams): void {
    doc.fillColor(INK).font('Helvetica-Bold').fontSize(15).text('Detailed findings', PAGE_MARGIN, PAGE_MARGIN);
    doc.moveDown(0.5);

    const sorted = p.findings.slice().sort((a, b) => SEVERITY_ORDER.indexOf(a.severity) - SEVERITY_ORDER.indexOf(b.severity));

    for (const f of sorted) {
        ensureSpace(doc, 90);
        const startY = doc.y;
        const color = severityColor(f.severity);

        doc.roundedRect(PAGE_MARGIN, startY, 58, 16, 4).fill(color);
        doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(8).text(SEVERITY_LABEL[f.severity].toUpperCase(), PAGE_MARGIN, startY + 4, { width: 58, align: 'center' });

        doc.fillColor(INK).font('Helvetica-Bold').fontSize(12).text(f.title, PAGE_MARGIN + 68, startY - 1, { width: doc.page.width - PAGE_MARGIN * 2 - 68 });
        doc.moveDown(0.3);

        doc.fillColor(MUTED).font('Helvetica-Oblique').fontSize(9.5).text(f.impact, PAGE_MARGIN, doc.y, { width: doc.page.width - PAGE_MARGIN * 2, lineGap: 2 });
        doc.moveDown(0.4);

        writeLabeledBlock(doc, 'Technical details', f.description);
        if (f.affected_url) writeLabeledBlock(doc, 'Affected URL', f.affected_url);
        writeLabeledBlock(doc, 'How to fix it', f.remediation);
        if (f.reference_links?.length) writeLabeledBlock(doc, 'References', f.reference_links.join('\n'));

        doc.moveDown(0.4);
        doc.moveTo(PAGE_MARGIN, doc.y).lineTo(doc.page.width - PAGE_MARGIN, doc.y).strokeColor(LINE).stroke();
        doc.moveDown(0.6);
    }
}

function writeLabeledBlock(doc: PDFKit.PDFDocument, label: string, text: string): void {
    doc.fillColor(MUTED).font('Helvetica-Bold').fontSize(8).text(label.toUpperCase(), PAGE_MARGIN, doc.y);
    doc.fillColor(INK).font('Helvetica').fontSize(9.5).text(text, PAGE_MARGIN, doc.y + 2, { width: doc.page.width - PAGE_MARGIN * 2, lineGap: 2 });
    doc.moveDown(0.4);
}

function ensureSpace(doc: PDFKit.PDFDocument, needed: number): void {
    if (doc.y + needed > doc.page.height - 60) doc.addPage();
}
