-- DomainIQ schema (Postgres). Idempotent: safe to run on every deploy.
--
-- Primary/foreign keys use SERIAL/INTEGER rather than BIGSERIAL/BIGINT on
-- purpose: node-postgres returns int8 (bigint) columns as strings to avoid
-- silent precision loss, which would clash with the `id: number` types
-- used throughout the app. int4's ~2.1 billion range is more than enough
-- for these tables.

CREATE TABLE IF NOT EXISTS users (
    id                  SERIAL PRIMARY KEY,
    email               TEXT NOT NULL UNIQUE,
    password_hash       TEXT NOT NULL,
    email_verified_at   TIMESTAMPTZ,
    plan                TEXT NOT NULL DEFAULT 'free',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS email_tokens (
    id          SERIAL PRIMARY KEY,
    user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token       TEXT NOT NULL UNIQUE,
    type        TEXT NOT NULL CHECK (type IN ('verify', 'reset')),
    expires_at  TIMESTAMPTZ NOT NULL,
    used_at     TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS watchlist (
    id          SERIAL PRIMARY KEY,
    user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    domain      TEXT NOT NULL,
    label       TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE(user_id, domain)
);

-- Every valuation ever computed, so a user's dashboard can chart how an
-- estimate has moved over time (comps dataset / algorithm updates shift it).
CREATE TABLE IF NOT EXISTS valuations (
    id              SERIAL PRIMARY KEY,
    domain          TEXT NOT NULL,
    score           DOUBLE PRECISION NOT NULL,
    low_usd         DOUBLE PRECISION NOT NULL,
    mid_usd         DOUBLE PRECISION NOT NULL,
    high_usd        DOUBLE PRECISION NOT NULL,
    confidence      TEXT NOT NULL,
    breakdown_json  JSONB NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_valuations_domain ON valuations(domain);
CREATE INDEX IF NOT EXISTS idx_valuations_domain_created ON valuations(domain, created_at DESC);

-- Curated public comparable sales, used to anchor the heuristic estimate
-- to real market data instead of a purely synthetic formula.
CREATE TABLE IF NOT EXISTS comps (
    id              SERIAL PRIMARY KEY,
    domain          TEXT NOT NULL UNIQUE,
    tld             TEXT NOT NULL,
    sale_price_usd  DOUBLE PRECISION NOT NULL,
    sale_year       INTEGER,
    word_count      INTEGER NOT NULL,
    char_count      INTEGER NOT NULL,
    category        TEXT,
    source_note     TEXT
);

CREATE INDEX IF NOT EXISTS idx_comps_tld ON comps(tld);
CREATE INDEX IF NOT EXISTS idx_comps_category ON comps(category);

-- Event-log rate limiting: serverless functions have no shared in-process
-- memory between invocations, so counters must live in the database.
CREATE TABLE IF NOT EXISTS rate_limit_events (
    id          SERIAL PRIMARY KEY,
    bucket      TEXT NOT NULL,
    client_key  TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_rate_limit_lookup ON rate_limit_events(bucket, client_key, created_at);

-- Newsletter: single opt-in with a per-subscriber unsubscribe token (no
-- login required for either subscribing or unsubscribing). Content for
-- each issue is supplied by the site owner via scripts/send-newsletter.ts,
-- not generated by the app.
CREATE TABLE IF NOT EXISTS newsletter_subscribers (
    id                  SERIAL PRIMARY KEY,
    email               TEXT NOT NULL UNIQUE,
    unsubscribe_token   TEXT NOT NULL UNIQUE,
    subscribed_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    unsubscribed_at     TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_newsletter_active ON newsletter_subscribers(email) WHERE unsubscribed_at IS NULL;
