// Sends a newsletter issue to all active subscribers.
//
// Usage:
//   npm run newsletter:send -- --subject "This week's picks" --file issue.html --yes
//   npm run newsletter:send -- --subject "..." --file issue.html          (dry run — no --yes, nothing is sent)
//
// `issue.html` is the content body only (a fragment, not a full HTML
// document) — content for every issue is written by you, not generated by
// this app. It gets wrapped in a minimal branded template with a
// per-recipient unsubscribe link automatically appended.
import { readFileSync } from 'node:fs';
import { Resend } from 'resend';
import { getPool } from '../src/lib/db';

function parseArgs(argv: string[]) {
    const args: Record<string, string | boolean> = {};
    for (let i = 0; i < argv.length; i++) {
        const arg = argv[i];
        if (arg?.startsWith('--')) {
            const key = arg.slice(2);
            const next = argv[i + 1];
            if (next && !next.startsWith('--')) {
                args[key] = next;
                i++;
            } else {
                args[key] = true;
            }
        }
    }
    return args;
}

function renderIssue(subject: string, bodyHtml: string, unsubscribeUrl: string): string {
    return `
    <div style="font-family: system-ui, -apple-system, sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="padding: 16px 0; border-bottom: 1px solid #e2e8f0;">
        <strong style="font-size: 18px;">DomainIQ</strong>
      </div>
      <div style="padding: 24px 0; color: #1e293b; line-height: 1.6;">
        ${bodyHtml}
      </div>
      <div style="padding: 16px 0; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 12px;">
        You're receiving this because you subscribed to the DomainIQ newsletter.
        <a href="${unsubscribeUrl}" style="color: #94a3b8;">Unsubscribe</a>
      </div>
    </div>
  `.trim();
}

async function main() {
    const args = parseArgs(process.argv.slice(2));
    const subject = typeof args.subject === 'string' ? args.subject : null;
    const file = typeof args.file === 'string' ? args.file : null;
    const confirmed = args.yes === true;

    if (!subject || !file) {
        console.error('Usage: npm run newsletter:send -- --subject "..." --file issue.html [--yes]');
        process.exit(1);
    }

    const apiKey = process.env.RESEND_API_KEY;
    if (confirmed && !apiKey) {
        console.error('RESEND_API_KEY is not set — cannot send.');
        process.exit(1);
    }

    const bodyHtml = readFileSync(file, 'utf-8');
    const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000';
    const from = process.env.EMAIL_FROM || 'DomainIQ <onboarding@resend.dev>';

    const pool = getPool();
    const { rows: subscribers } = await pool.query<{ email: string; unsubscribe_token: string }>(
        'SELECT email, unsubscribe_token FROM newsletter_subscribers WHERE unsubscribed_at IS NULL',
    );

    console.log(`Subject: ${subject}`);
    console.log(`Recipients: ${subscribers.length}`);

    if (!confirmed) {
        console.log('\nDry run (no emails sent). Pass --yes to actually send.');
        console.log('\nPreview of the rendered email (first recipient, or a placeholder if none):');
        const sampleToken = subscribers[0]?.unsubscribe_token ?? 'PREVIEW_TOKEN';
        console.log(renderIssue(subject, bodyHtml, `${baseUrl}/api/newsletter/unsubscribe?token=${sampleToken}`));
        await pool.end();
        return;
    }

    if (subscribers.length === 0) {
        console.log('No active subscribers — nothing to send.');
        await pool.end();
        return;
    }

    const resend = new Resend(apiKey);
    const BATCH_SIZE = 5;
    const BATCH_DELAY_MS = 1200; // stays comfortably under Resend's ~10 req/sec limit

    let sent = 0;
    let failed = 0;

    for (let i = 0; i < subscribers.length; i += BATCH_SIZE) {
        const batch = subscribers.slice(i, i + BATCH_SIZE);
        await Promise.all(
            batch.map(async (sub) => {
                const unsubscribeUrl = `${baseUrl}/api/newsletter/unsubscribe?token=${sub.unsubscribe_token}`;
                const { error } = await resend.emails.send({
                    from,
                    to: sub.email,
                    subject,
                    html: renderIssue(subject, bodyHtml, unsubscribeUrl),
                });
                if (error) {
                    failed++;
                    console.error(`  Failed: ${sub.email} — ${error.name}: ${error.message}`);
                } else {
                    sent++;
                }
            }),
        );
        console.log(`Progress: ${Math.min(i + BATCH_SIZE, subscribers.length)}/${subscribers.length}`);
        if (i + BATCH_SIZE < subscribers.length) {
            await new Promise((r) => setTimeout(r, BATCH_DELAY_MS));
        }
    }

    console.log(`\nDone. Sent: ${sent}, Failed: ${failed}`);
    await pool.end();
}

main().catch((err) => {
    console.error('Newsletter send failed:', err);
    process.exitCode = 1;
});
